import = [
    'C:\dev\src\task_runner\examples\dynamic_requirements.py',
    'C:\dev\src\task_runner\examples\dynamic_requirements2.py',
]

[logging]
version = 1
disable_existing_loggers = false

# logs format
[logging.formatters.simple]
format = "{levelname:8} {asctime} {module}:{lineno} {message}"
style = "{"
datefmt = "%Y-%m-%d %H:%M:%S"

# write logs to console
[logging.handlers.console]
level = "DEBUG"
class = "logging.StreamHandler"
formatter = "simple"

# trun worker logging
[logging.loggers.trun-interface]
handlers = ["console"]
level = "INFO"
disabled = false
propagate = false

# trund logging
[logging.loggers.trun]
handlers = ["console"]
level = "INFO"
disabled = false
propagate = false

# trund builded on tornado
[logging.loggers.tornado]
handlers = ["console"]
level = "INFO"
disabled = false
propagate = false

# custom logger for "project"
[logging.loggers.project]
handlers = ["console"]
level = "DEBUG"
disabled = false
propagate = false
