# config_with_table_array.toml
title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00

table_array_key = [
  {key1 = "value1", key2 = "value2"},
  {key1 = "value3", key2 = "value4"}
]